#!/usr/bin/env python3
"""
Create a sitecustomize.py injection shim for TunableOps.

Problem: PYTORCH_TUNABLEOP_FILENAME env var does NOT auto-load a CSV in PyTorch 2.9+.
It only controls the write destination. Loading requires torch.cuda.tunable.read_file()
called inside the target process.

vLLM spawns EngineCore as a subprocess (VLLM_WORKER_MULTIPROC_METHOD=spawn). Any
sitecustomize.py on PYTHONPATH runs in every Python process, including EngineCore.

Solution:
  1. This script creates PYTHONPATH_DIR/sitecustomize.py with a read_file() call.
  2. Set PYTHONPATH=PYTHONPATH_DIR before starting vLLM.
  3. Every subprocess (EngineCore + workers) loads the tuned CSV automatically.

Usage:
    python create_inject.py \\
        --tuned-csv  optimized/tuned_gemm.csv \\
        --output-dir optimized/pypath

Then start vLLM:
    PYTORCH_TUNABLEOP_ENABLED=1 \\
    PYTHONPATH=optimized/pypath:$PYTHONPATH \\
    python3 -m vllm.entrypoints.openai.api_server ...

Verification (check vLLM log):
    grep "tunableops_inject" vllm.log
    # Expected: [tunableops_inject] Loaded N tuned entries from ...
"""
import argparse
import os
import sys


SITECUSTOMIZE_TEMPLATE = '''\
"""
TunableOps injection shim — generated by create_inject.py.
Loads the tuned GEMM CSV via Python API (env var PYTORCH_TUNABLEOP_FILENAME
does NOT auto-load in PyTorch 2.9+; only write is supported via env var).
Runs in every spawned subprocess including vLLM EngineCore.
"""
import os as _os

_TUNED_CSV = {tuned_csv!r}
_ENABLED   = _os.environ.get("PYTORCH_TUNABLEOP_ENABLED", "0") == "1"

if _ENABLED and _os.path.exists(_TUNED_CSV):
    try:
        import torch as _torch
        if _torch.cuda.is_available():
            _torch.cuda.tunable.enable(val=True)
            _torch.cuda.tunable.tuning_enable(val=False)
            _torch.cuda.tunable.read_file(_TUNED_CSV)
            _n = len(_torch.cuda.tunable.get_results())
            print(f"[tunableops_inject] Loaded {{_n}} tuned entries from {{_TUNED_CSV}}",
                  flush=True)
    except Exception as _e:
        print(f"[tunableops_inject] Warning: {{_e}}", flush=True)
'''


def main():
    parser = argparse.ArgumentParser(description="Create TunableOps sitecustomize.py shim")
    parser.add_argument("--tuned-csv",  required=True, help="Path to tuned GEMM CSV")
    parser.add_argument("--output-dir", required=True, help="Directory to write sitecustomize.py into")
    args = parser.parse_args()

    tuned_csv = os.path.abspath(args.tuned_csv)
    if not os.path.exists(tuned_csv):
        print(f"ERROR: tuned CSV not found: {tuned_csv}", file=sys.stderr)
        sys.exit(1)

    os.makedirs(args.output_dir, exist_ok=True)
    out_path = os.path.join(args.output_dir, "sitecustomize.py")

    with open(out_path, "w") as f:
        f.write(SITECUSTOMIZE_TEMPLATE.format(tuned_csv=tuned_csv))

    print(f"Created: {out_path}")
    print()
    print("To activate, start vLLM with:")
    print(f"  PYTORCH_TUNABLEOP_ENABLED=1 \\")
    print(f"  PYTHONPATH={os.path.abspath(args.output_dir)}:${{PYTHONPATH:-}} \\")
    print(f"  python3 -m vllm.entrypoints.openai.api_server ...")
    print()
    print("Verify in vLLM log:")
    print("  grep 'tunableops_inject' vllm.log")

    n = sum(1 for l in open(tuned_csv) if l.startswith("Gemm"))
    print(f"\nTuned entries that will be loaded: {n}")


if __name__ == "__main__":
    main()
